### ISSUE TITLE
Client ID & Is this permitted by Sony?

### ISSUE THREAD

**Issue by michaelonubogu** [jhewt/gumer-psn#14]
I was planning on using this to add functionality for an app I'm working on currently, but after going through the code, I noticed your clientId is hardcoded within the psn.js file.

I imagine this is something that would come with access to the API from Sony. I just wanted to ask if there is a way to acquire a client Id directly from sony, or if while using the code, I would have to use your clientId.

Just trying to avoid any potential issues from Sony

**Comment by jhewt** [comment]
Yes, it is required to access their API. It is hardcoded because I've been tried on many different phones to check if that's something related to the user's device or account but apparently not.
Maybe that has change in the last few months, I've to update the current API to make it work again. I guess that'll be next week.

If SONY is not "ok" with this, they can easily shut down this repository. It's free software, so, neither you or me will get on trouble.
