### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by vandalnet** [jhewt/gumer-psn#15]
Since last Friday July the 3rd the API is not working anymore. It is not able to obtain the access_token due to changes in the login page apparently made by Sony. Does anyone else have this problem?

**Comment by ezibit** [comment]
dev will update be patient

Kind regards,
*EZi-BiT - *Tailored Colocation and Digital Currency solutions
*Trent Churchill* - Wholesale Data Center Consultant
Ph: +61 425 362 131
trent@triplebgroup.net
Triple B Group Pty Ltd.
ACN: 168 989 080
This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Triple B Group
Pty Ltd is not responsible for errors or omissions in this message and
denies any responsibility for any damage arising from the use of e-mail.
Any opinion and other statement contained in this message and any
attachment are solely those of the author and do not necessarily represent
those of the company.

**Comment by jhewt** [comment]
I've been told of issue yesterday, I'll be updating in the following week. I've been busy moving to my new location. Atm I do not have access to a PS3/PS4 to test if the data coming from this API matches the content on the consoles.

Thanks for the patience!

**Comment by vandalnet** [comment]
If you need any help to troubleshoot it count on me (I speak Spanish too)

**Comment by songoku119** [comment]
In to help if I can as well.  Was making an API in .net to use this and was trying to figure out why my request stopped working.

**Comment by pcmantinker** [comment]
It looks like the current implementation of this repository's script looks for the authCode/code in the redirect location, but this has changed to using a JavaScript redirect. Understandably, anything attempting to pull the code from the redirect location will fail. In my client implementation for the iPhone app, I look for this line in the final response:
```javascript
location.href="com.playstation.PlayStationApp://redirect?code={code}&state={state}";
```

The code is still 6 characters long. I'm guessing that the location.href will look something more like the following. Note, I have not analyzed the Android application traffic so I can't confirm at the moment:
```javascript
location.href="com.scee.psxandroid.scecompcall://redirect?code={code}&state={state}";
```

All of my code is in .NET with HttpClient, but if anyone wants, I could see about making a pull request for the JavaScript code here. 

I may look at open sourcing my .NET PSN API since most of the stuff I reverse engineered is already public here but from the Android application traffic and not the iPhone application traffic. It might further benefit everyone to have both the Android and iPhone application clients open sourced.

**Comment by songoku119** [comment]
I agree about open sourcing as it would benefit all.  I will take a look at the traffic logs I have saved and see what is coming in the response.  I would be interested in seeing your implementation too using httpclient.  Didn't think about going that route.

**Comment by viskem** [comment]
so ..how to fix it T_T

**Comment by elminsterjimmy** [comment]
There's an open sourcing api available in https://github.com/elminsterjimmy/PSN-API.

**Comment by songoku119** [comment]
Thanks. I'll check it out.

**Comment by pcmantinker** [comment]
Here's another API/Application build on .NET for Windows Phone 8: https://github.com/drasticactions/FoulPlay

**Comment by songoku119** [comment]
Awesome ! Thanks for sharing

**Comment by jhewt** [comment]
Hello, sorry I've let you all down. Lately I'm incredible busy with work, so I didn't had much free time to do some "cracking" to PSN's App.
However, today I decided to give up my free time to update this repo.
BUT auth.api.sonyentertainmentnetwork.com isn't responding for me at the moment, it doesn't return a single byte. I've checked with a non-rooted phone (just in case) with a different conection in case they banned me for reverse engineering.

Is the server working? It has stopped working for quite a while now?
