### ISSUE TITLE
Error_code":4151,"error":"unauthorized_client","error_description":"Client does not have grant type

### ISSUE THREAD

**Issue by isFakeAccount** [jhewt/gumer-psn#42]
I am getting the following error 

> {"error_code":4151,"error":"unauthorized_client","error_description":"Client does not have grant type: [\"implicit\",\"authorization_code\"]","docs":"http://central-auth.p1-np-eib.prod.navcloud.sonynei.net/docs/#api/centralauthservice/v1/oauth/authorize/get"}

Where in the android app can I get the client ID and client secret?

**Comment by nirina-jacques** [comment]
I have same issue, where can I get client_id and client secret ?

**Comment by jhewt** [comment]
Hi there,

This repo has been discontinued a long time ago since Sony started using Google's Catpcha in all of their web-based sites.
This project was based on an old Playstation hybrid-app and pretty much was a simulation of the login flow but it got handicapped with those captchas, rendering this repo useless.

I'm sorry for not disclosing this repo is discontinued and broken, I'll archive this so I don't make more devs waste their time.
